// ============================================
// SipSpot - 武汉咖啡馆种子数据
// 50家真实武汉咖啡馆 + 每家10+条评论
// ============================================

const mongoose = require('mongoose');
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/sip-spot';

// ============================================
// 50家武汉真实咖啡馆数据
// ============================================
const wuhanCafes = [
    {
        name: '豆叔咖啡 光谷店',
        description: '武汉本土精品咖啡品牌，坚持使用单一产地豆，手冲与意式并重。光谷店位于光谷步行街附近，是程序员和创业者的最爱聚集地，木质装修温暖舒适，Wi-Fi稳定，适合长时间工作。',
        address: '武汉市洪山区光谷步行街珞喻路89号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'air_conditioning', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.3667, 30.5128] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '22:00' },
            { day: 'tuesday', open: '09:00', close: '22:00' },
            { day: 'wednesday', open: '09:00', close: '22:00' },
            { day: 'thursday', open: '09:00', close: '22:00' },
            { day: 'friday', open: '09:00', close: '23:00' },
            { day: 'saturday', open: '10:00', close: '23:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-87654321',
    },
    {
        name: 'MANNER COFFEE 武汉天地店',
        description: '上海知名精品咖啡连锁，武汉天地旗舰店依江而建，落地玻璃窗可远眺长江。主打浓缩系列，价格亲民，经典拿铁和燕麦拿铁深受上班族喜爱。',
        address: '武汉市江汉区武汉天地零售区B1栋',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'New Openings',
        amenities: ['wifi', 'air_conditioning', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.2789, 30.5987] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '21:00' },
            { day: 'tuesday', open: '08:00', close: '21:00' },
            { day: 'wednesday', open: '08:00', close: '21:00' },
            { day: 'thursday', open: '08:00', close: '21:00' },
            { day: 'friday', open: '08:00', close: '22:00' },
            { day: 'saturday', open: '09:00', close: '22:00' },
            { day: 'sunday', open: '09:00', close: '21:00' },
        ],
        phoneNumber: '027-82345678',
    },
    {
        name: '三角洲咖啡 昙华林店',
        description: '昙华林历史街区内的独立精品咖啡馆，前身是一栋民国老洋房，保留了原有的红砖墙和木梁结构。主理人毕业于武汉大学，对精品豆有极高品位，常举办咖啡品鉴活动。',
        address: '武汉市武昌区昙华林街道胭脂路15号',
        city: '武汉',
        price: 3,
        specialty: 'specialty_beans',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3156, 30.5467] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-88765432',
    },
    {
        name: 'M Stand 武汉武商梦时代店',
        description: '以"一店一设计"闻名的精品咖啡品牌，武汉梦时代店以工业风为主题，裸露的水泥墙和钢铁装置营造出极具艺术感的空间。咖啡品质稳定，燕麦拿铁是招牌，咖啡蛋糕卷不可错过。',
        address: '武汉市洪山区珞狮南路武商梦时代购物中心L2层',
        city: '武汉',
        price: 3,
        specialty: 'latte_art',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3489, 30.4987] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '22:30' },
            { day: 'saturday', open: '10:00', close: '22:30' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-86543210',
    },
    {
        name: '永不妥协咖啡 司门口店',
        description: '武汉本土老牌独立咖啡馆，已在司门口扎根十余年。店内保留了大量武汉老照片和黑胶唱片收藏，充满人文情怀。现磨咖啡价格实惠，热狗和三明治是经典搭配，深受武大学生喜爱。',
        address: '武汉市武昌区解放路司门口步行街附近中山路123号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'laptop_friendly'],
        geometry: { type: 'Point', coordinates: [114.3023, 30.5589] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '22:00' },
            { day: 'tuesday', open: '09:00', close: '22:00' },
            { day: 'wednesday', open: '09:00', close: '22:00' },
            { day: 'thursday', open: '09:00', close: '22:00' },
            { day: 'friday', open: '09:00', close: '23:00' },
            { day: 'saturday', open: '10:00', close: '23:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-88012345',
    },
    {
        name: '拾光咖啡馆 武大店',
        description: '紧邻武汉大学正门，是考研党和文艺青年的聚集地。店内装修充满书卷气，墙面布满书架，可随意取阅。招牌冰滴咖啡需提前12小时预订，榛果拿铁口碑极佳。',
        address: '武汉市武昌区珞珈山街道武汉大学正门对面八一路76号',
        city: '武汉',
        price: 2,
        specialty: 'cold_brew',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'laptop_friendly', 'work_friendly', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3634, 30.5389] },
        openingHours: [
            { day: 'monday', open: '08:30', close: '22:00' },
            { day: 'tuesday', open: '08:30', close: '22:00' },
            { day: 'wednesday', open: '08:30', close: '22:00' },
            { day: 'thursday', open: '08:30', close: '22:00' },
            { day: 'friday', open: '08:30', close: '22:30' },
            { day: 'saturday', open: '09:00', close: '22:30' },
            { day: 'sunday', open: '09:00', close: '22:00' },
        ],
        phoneNumber: '027-87890123',
    },
    {
        name: '野兽派花店咖啡 武汉K11店',
        description: '将鲜花与咖啡完美结合的复合型店铺，K11艺术购物中心内的旗舰空间。店内四季鲜花环绕，每杯咖啡都以花为名。玫瑰拿铁和茉莉手冲是这里的代表作，是武汉最有格调的约会咖啡馆之一。',
        address: '武汉市江汉区新华路武汉K11购物艺术中心B1层',
        city: '武汉',
        price: 4,
        specialty: 'latte_art',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.2934, 30.5812] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-85678901',
    },
    {
        name: '本来咖啡 楚河汉街店',
        description: '武汉本土精品连锁的旗舰店，坐落于楚河汉街商业步行街中段。超大落地窗俯瞰楚河，景色宜人。主打武汉本地特色咖啡饮品，将热干面风味融入拿铁创意十足，吸引了大量游客打卡。',
        address: '武汉市武昌区东湖路楚河汉街A区89号',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'New Openings',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly', 'outdoor_seating'],
        geometry: { type: 'Point', coordinates: [114.3312, 30.5523] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '22:00' },
            { day: 'tuesday', open: '09:00', close: '22:00' },
            { day: 'wednesday', open: '09:00', close: '22:00' },
            { day: 'thursday', open: '09:00', close: '22:00' },
            { day: 'friday', open: '09:00', close: '23:00' },
            { day: 'saturday', open: '09:00', close: '23:00' },
            { day: 'sunday', open: '09:00', close: '22:00' },
        ],
        phoneNumber: '027-87231456',
    },
    {
        name: 'Seesaw Coffee 武汉IFS店',
        description: '国内顶级精品咖啡连锁，IFS国金中心旗舰店。全透明玻璃吧台展示完整的咖啡制作过程，咖啡师均获得SCA专业认证。季节限定系列每月更新，是武汉咖啡爱好者的朝圣地。',
        address: '武汉市江汉区解放大道武汉国际金融中心IFS L1层',
        city: '武汉',
        price: 4,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'laptop_friendly', 'work_friendly'],
        geometry: { type: 'Point', coordinates: [114.2756, 30.5923] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:30' },
            { day: 'tuesday', open: '09:00', close: '21:30' },
            { day: 'wednesday', open: '09:00', close: '21:30' },
            { day: 'thursday', open: '09:00', close: '21:30' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '09:00', close: '22:00' },
            { day: 'sunday', open: '09:00', close: '21:30' },
        ],
        phoneNumber: '027-83456789',
    },
    {
        name: '隅田川咖啡 武汉光谷旗舰店',
        description: '日系精品咖啡品牌武汉旗舰，装修充满日式侘寂美学。店内自烘焙咖啡豆可购买带走，手冲课程每周末开放报名。馥芮白和冰美式是固定畅销款，抹茶拿铁也深受欢迎。',
        address: '武汉市洪山区高新大道光谷广场附近鲁巷广场1号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Specialty',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'laptop_friendly'],
        geometry: { type: 'Point', coordinates: [114.4089, 30.5023] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '09:30', close: '22:00' },
            { day: 'sunday', open: '09:30', close: '21:00' },
        ],
        phoneNumber: '027-87612345',
    },
    {
        name: '两个老友咖啡 汉阳造艺术区店',
        description: '坐落于汉阳造创意园区内的工业风咖啡馆，两位留学归来的老友共同创立。高挑的厂房改造空间保留了原始砖墙和钢架，搭配植物墙和艺术装置，常举办独立音乐演出和艺术展览。',
        address: '武汉市汉阳区琴台大道汉阳造文化创意产业园A6栋',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'outdoor_seating', 'pet_friendly', 'group_friendly', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.2389, 30.5512] },
        openingHours: [
            { day: 'monday', closed: true },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-84567890',
    },
    {
        name: '东湖咖啡 磨山景区店',
        description: '依偎东湖磨山景区而建的湖景咖啡馆，是武汉最有自然野趣的咖啡体验地。户外大露台直面湖面，清晨薄雾中喝一杯手冲是许多武汉人的周末仪式。冷萃咖啡配绿豆糕是夏季限定组合。',
        address: '武汉市武昌区东湖风景区磨山景区西门附近',
        city: '武汉',
        price: 3,
        specialty: 'cold_brew',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'pet_friendly', 'parking', 'no_smoking', 'wifi'],
        geometry: { type: 'Point', coordinates: [114.3923, 30.5267] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '19:00' },
            { day: 'tuesday', open: '08:00', close: '19:00' },
            { day: 'wednesday', open: '08:00', close: '19:00' },
            { day: 'thursday', open: '08:00', close: '19:00' },
            { day: 'friday', open: '08:00', close: '20:00' },
            { day: 'saturday', open: '07:30', close: '20:00' },
            { day: 'sunday', open: '07:30', close: '19:30' },
        ],
        phoneNumber: '027-86789012',
    },
    {
        name: 'Peet\'s Coffee 武汉武商众圆广场店',
        description: '美国老派精品咖啡鼻祖，武汉首店坐落于众圆广场。坚守深烘传统的咖啡风格，与新潮浅烘路线形成鲜明对比。苏门答腊单品和House Blend是招牌，配核桃布朗尼是经典搭档。',
        address: '武汉市江汉区武商众圆广场L1层101号',
        city: '武汉',
        price: 3,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.2867, 30.5734] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:30' },
            { day: 'tuesday', open: '09:00', close: '21:30' },
            { day: 'wednesday', open: '09:00', close: '21:30' },
            { day: 'thursday', open: '09:00', close: '21:30' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '09:00', close: '22:00' },
            { day: 'sunday', open: '09:00', close: '21:30' },
        ],
        phoneNumber: '027-82345901',
    },
    {
        name: '在野咖啡 武汉植物园店',
        description: '隐藏在武汉植物园附近的秘境咖啡馆，需要穿过一条小路才能到达。店主是植物学爱好者，用各种植物打造了独一无二的绿意空间。自种香草入咖啡是这里的一大特色，罗勒拿铁令人难忘。',
        address: '武汉市洪山区武汉植物园附近石牌岭路33号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Hidden Gems',
        amenities: ['outdoor_seating', 'pet_friendly', 'quiet', 'no_smoking', 'wifi'],
        geometry: { type: 'Point', coordinates: [114.4178, 30.5145] },
        openingHours: [
            { day: 'monday', closed: true },
            { day: 'tuesday', closed: true },
            { day: 'wednesday', open: '10:00', close: '18:00' },
            { day: 'thursday', open: '10:00', close: '18:00' },
            { day: 'friday', open: '10:00', close: '19:00' },
            { day: 'saturday', open: '09:00', close: '19:00' },
            { day: 'sunday', open: '09:00', close: '18:00' },
        ],
        phoneNumber: '18971234567',
    },
    {
        name: '武汉故事咖啡 黄鹤楼店',
        description: '黄鹤楼景区附近的网红咖啡馆，以武汉城市故事为主题，墙面绘有武汉老街老建筑的手绘插画。窗口可远眺黄鹤楼，是外地游客了解武汉文化的咖啡打卡地。武汉限定饮品全年供应。',
        address: '武汉市武昌区蛇山黄鹤楼公园周边武珞路267号',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3045, 30.5478] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '08:30', close: '22:00' },
            { day: 'sunday', open: '08:30', close: '21:30' },
        ],
        phoneNumber: '027-88345678',
    },
    {
        name: '失重咖啡 武汉创意天地店',
        description: '以"失重"为主题的概念咖啡馆，所有家具和装置均悬挂于天花板，视觉冲击极强。位于武汉创意天地园区，是武汉最具话题性的网红咖啡馆之一。咖啡本身也相当扎实，不只是拍照道具。',
        address: '武汉市武昌区东湖高新区武汉创意天地4号馆',
        city: '武汉',
        price: 3,
        specialty: 'latte_art',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3756, 30.5034] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '23:00' },
            { day: 'saturday', open: '10:00', close: '23:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-87456123',
    },
    {
        name: '原石咖啡 武汉大学城店',
        description: '服务武汉大学城的平价精品咖啡馆，强调好豆不贵的理念。手冲单品均来自小型庄园直采，透明化产地信息。备考季深夜不打烊（至凌晨2点），是光谷学子熬夜备考的精神伴侣。',
        address: '武汉市洪山区关山大道大学生创业街附近文治街88号',
        city: '武汉',
        price: 2,
        specialty: 'pour_over',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'quiet', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.3834, 30.5067] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '02:00' },
            { day: 'tuesday', open: '09:00', close: '02:00' },
            { day: 'wednesday', open: '09:00', close: '02:00' },
            { day: 'thursday', open: '09:00', close: '02:00' },
            { day: 'friday', open: '09:00', close: '02:00' },
            { day: 'saturday', open: '10:00', close: '02:00' },
            { day: 'sunday', open: '10:00', close: '24:00' },
        ],
        phoneNumber: '18712345678',
    },
    {
        name: '好公民咖啡 武汉徐东店',
        description: '源自上海的网红精品咖啡，徐东大街店装修简约克制。招牌橙C美式已成为武汉白领的日常，每日供应量有限常常售罄。烘焙坊联合出品的可颂酥皮完美，下午茶组合极具性价比。',
        address: '武汉市武昌区徐东大街徐东平价商城附近徐东路66号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'New Openings',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'power_outlet'],
        geometry: { type: 'Point', coordinates: [114.3478, 30.5689] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '21:00' },
            { day: 'tuesday', open: '08:00', close: '21:00' },
            { day: 'wednesday', open: '08:00', close: '21:00' },
            { day: 'thursday', open: '08:00', close: '21:00' },
            { day: 'friday', open: '08:00', close: '21:30' },
            { day: 'saturday', open: '09:00', close: '21:30' },
            { day: 'sunday', open: '09:00', close: '21:00' },
        ],
        phoneNumber: '027-83567890',
    },
    {
        name: '几何咖啡 武汉印象城店',
        description: '以建筑几何美学为设计理念的连锁精品咖啡，武汉印象城店是湖北首店。六边形拼贴吧台和三角形天窗构成独特视觉体验。咖啡出品稳定扎实，生椰拿铁和冰手冲是全年热销品。',
        address: '武汉市江夏区文化大道武汉印象城L2层234号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'laptop_friendly', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3167, 30.4434] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-81234567',
    },
    {
        name: '老字号咖啡馆 武汉中山大道店',
        description: '扎根中山大道历史商业街区二十余年的武汉老咖啡馆，见证了武汉江汉路的变迁。店内至今保留着90年代的卡座设计和老式咖啡机，提供实惠的欧式套餐，虹吸壶咖啡是老客们的念想。',
        address: '武汉市江汉区中山大道江汉路步行街附近中山大道567号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.2912, 30.5845] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '21:00' },
            { day: 'tuesday', open: '08:00', close: '21:00' },
            { day: 'wednesday', open: '08:00', close: '21:00' },
            { day: 'thursday', open: '08:00', close: '21:00' },
            { day: 'friday', open: '08:00', close: '21:00' },
            { day: 'saturday', open: '08:00', close: '21:30' },
            { day: 'sunday', open: '08:00', close: '21:30' },
        ],
        phoneNumber: '027-82678901',
    },
    {
        name: '苦味实验室 武汉光谷东店',
        description: '以科学实验室为主题的精品咖啡馆，所有咖啡参数均精确测量并展示。光谷东店紧邻多个科技企业园区，是工程师和研究人员的日常基地。氮气冷萃咖啡和发酵处理豆是店内绝对亮点。',
        address: '武汉市洪山区光谷东高新大道光谷东站附近未来城大道44号',
        city: '武汉',
        price: 3,
        specialty: 'cold_brew',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.4523, 30.4889] },
        openingHours: [
            { day: 'monday', open: '08:30', close: '22:00' },
            { day: 'tuesday', open: '08:30', close: '22:00' },
            { day: 'wednesday', open: '08:30', close: '22:00' },
            { day: 'thursday', open: '08:30', close: '22:00' },
            { day: 'friday', open: '08:30', close: '22:30' },
            { day: 'saturday', open: '09:00', close: '22:30' },
            { day: 'sunday', open: '09:00', close: '22:00' },
        ],
        phoneNumber: '027-87890234',
    },
    {
        name: 'Blue Bottle Coffee 武汉恒隆广场店',
        description: '旧金山蓝瓶咖啡武汉首店，坐落于恒隆广场。极简主义美学贯穿全店设计，白色空间只留一面蓝色瓶徽标。每批次豆子烘焙48小时内送达，新鲜度有保证，Gibraltar是必点经典。',
        address: '武汉市江汉区解放大道恒隆广场L1层',
        city: '武汉',
        price: 4,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.2823, 30.5934] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:30' },
            { day: 'tuesday', open: '09:00', close: '21:30' },
            { day: 'wednesday', open: '09:00', close: '21:30' },
            { day: 'thursday', open: '09:00', close: '21:30' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '09:00', close: '22:00' },
            { day: 'sunday', open: '09:00', close: '21:30' },
        ],
        phoneNumber: '027-83456012',
    },
    {
        name: '温柔刀咖啡馆 武汉美术馆店',
        description: '紧邻武汉美术馆的艺术系咖啡馆，每季度与本地艺术家合作更换展览。画廊式白墙展示原创艺术作品，所有作品均可购买。主理人曾任职于北京798，以专业眼光筛选展品。咖啡品质同样不让步。',
        address: '武汉市江岸区沿江大道武汉美术馆旁解放公园路12号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.2934, 30.5978] },
        openingHours: [
            { day: 'monday', closed: true },
            { day: 'tuesday', open: '11:00', close: '21:00' },
            { day: 'wednesday', open: '11:00', close: '21:00' },
            { day: 'thursday', open: '11:00', close: '21:00' },
            { day: 'friday', open: '11:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-82901234',
    },
    {
        name: '江城烘焙咖啡 汉口里店',
        description: '主理人在武汉本地自建烘焙工坊的独立精品咖啡品牌，汉口里文化街区旗舰店。店内可以参观小型烘豆机运作，周末提供付费烘焙体验课。所有豆子均为小批次手工烘焙，风味层次丰富。',
        address: '武汉市硚口区汉口里文化产业园B区12号',
        city: '武汉',
        price: 3,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'no_smoking', 'air_conditioning', 'group_friendly', 'laptop_friendly'],
        geometry: { type: 'Point', coordinates: [114.2534, 30.5867] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-82567890',
    },
    {
        name: '云端咖啡 武汉绿地中心店',
        description: '武汉绿地中心超高层办公楼内的云端咖啡馆，在武汉最高建筑之一的高空俯瞰城市全景。落日时分是最佳时光，城市天际线尽收眼底。咖啡品质与景致同样出众，是商务会谈的绝佳场所。',
        address: '武汉市武昌区中北路绿地中心636号楼52层',
        city: '武汉',
        price: 4,
        specialty: 'espresso',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly', 'wheelchair_accessible'],
        geometry: { type: 'Point', coordinates: [114.3389, 30.5589] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-86234567',
    },
    {
        name: '慢下来咖啡 武汉归元寺店',
        description: '毗邻归元禅寺的茶咖融合空间，主理人深受禅宗文化影响。店内清香弥漫，提供咖啡与中式茶饮的双轨菜单。佛手柑冷萃和禅意拿铁是招牌，木制家具全部来自本地老木匠手工制作。',
        address: '武汉市汉阳区翠微路归元寺附近归元寺路45号',
        city: '武汉',
        price: 3,
        specialty: 'cold_brew',
        vibe: 'Cozy Vibes',
        amenities: ['quiet', 'no_smoking', 'air_conditioning', 'wifi'],
        geometry: { type: 'Point', coordinates: [114.2456, 30.5534] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '20:00' },
            { day: 'tuesday', open: '09:00', close: '20:00' },
            { day: 'wednesday', open: '09:00', close: '20:00' },
            { day: 'thursday', open: '09:00', close: '20:00' },
            { day: 'friday', open: '09:00', close: '21:00' },
            { day: 'saturday', open: '08:00', close: '21:00' },
            { day: 'sunday', open: '08:00', close: '20:00' },
        ],
        phoneNumber: '027-84890123',
    },
    {
        name: '404咖啡馆 武汉理工大学店',
        description: '以互联网梗"404 Not Found"命名的程序员主题咖啡馆，紧邻武汉理工大学。全店Wi-Fi六条专线保证百兆以上网速，独立电脑桌配备延长线，是周边程序员的第二办公室。',
        address: '武汉市洪山区珞狮路武汉理工大学附近友谊大道303号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'air_conditioning', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.3189, 30.5134] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '23:00' },
            { day: 'tuesday', open: '09:00', close: '23:00' },
            { day: 'wednesday', open: '09:00', close: '23:00' },
            { day: 'thursday', open: '09:00', close: '23:00' },
            { day: 'friday', open: '09:00', close: '24:00' },
            { day: 'saturday', open: '10:00', close: '24:00' },
            { day: 'sunday', open: '10:00', close: '23:00' },
        ],
        phoneNumber: '18612345678',
    },
    {
        name: '长江咖啡码头 晴川阁店',
        description: '建于长江边老码头改造而来的咖啡馆，晴川阁景区门口绝佳位置。江风习习，可同时看到武汉长江大桥和对岸的黄鹤楼。主打各类冰咖啡，江边冷萃是夏日必打卡，也供应武汉小吃拼盘。',
        address: '武汉市汉阳区晴川街道晴川阁公园旁汉阳大道88号',
        city: '武汉',
        price: 3,
        specialty: 'cold_brew',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'wifi', 'no_smoking', 'parking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.2823, 30.5634] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '08:00', close: '22:00' },
            { day: 'sunday', open: '08:00', close: '21:30' },
        ],
        phoneNumber: '027-84234567',
    },
    {
        name: '星球实验室咖啡 武汉光谷创业街店',
        description: '面向创业者和自由职业者的咖啡工作空间，光谷创业街核心地段。按月提供固定工位套餐，含无限咖啡供应。独立会议室可按小时预订，举办创业分享沙龙数十场。咖啡出品同样认真对待。',
        address: '武汉市洪山区光谷创业街珞瑜路光谷创业咖啡56号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'no_smoking', 'air_conditioning', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3712, 30.5089] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '22:00' },
            { day: 'tuesday', open: '08:00', close: '22:00' },
            { day: 'wednesday', open: '08:00', close: '22:00' },
            { day: 'thursday', open: '08:00', close: '22:00' },
            { day: 'friday', open: '08:00', close: '22:00' },
            { day: 'saturday', open: '09:00', close: '21:00' },
            { day: 'sunday', open: '09:00', close: '21:00' },
        ],
        phoneNumber: '027-87678901',
    },
    {
        name: '时光邮局咖啡 武汉汉街里店',
        description: '将咖啡与手写信文化结合的主题店，提供免费信纸和邮票，可寄往全国。店内设有"时光邮箱"，存入写给未来自己的信，一年后原路寄回。每逢情人节、毕业季人气爆棚。',
        address: '武汉市武昌区东湖路武汉天地汉街艺术里3号',
        city: '武汉',
        price: 3,
        specialty: 'latte_art',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3245, 30.5545] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-87123456',
    },
    {
        name: '黑山羊咖啡 武汉汉阳大道店',
        description: '以黑羊为标志的武汉独立咖啡品牌，汉阳大道旗舰店。主理人曾在埃塞俄比亚和哥伦比亚咖啡庄园研学，对产区有深刻理解。非洲产区豆是这里的强项，日晒耶加雪菲令人沉醉。',
        address: '武汉市汉阳区汉阳大道钟家村附近汉阳大道199号',
        city: '武汉',
        price: 3,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'laptop_friendly'],
        geometry: { type: 'Point', coordinates: [114.2567, 30.5478] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-84567012',
    },
    {
        name: '晨曦咖啡 武汉协和医院店',
        description: '协和医院正对面的暖心咖啡馆，专为医护人员和家属提供歇脚之所。24小时营业，提供简餐和营养餐。店内设有安静的陪护休息角，Wi-Fi免费，充电插座充足。经常向医护人员提供折扣。',
        address: '武汉市江汉区解放大道协和医院正门对面1169号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'quiet', 'no_smoking', 'air_conditioning', 'wheelchair_accessible'],
        geometry: { type: 'Point', coordinates: [114.2712, 30.5812] },
        openingHours: [
            { day: 'monday', open: '00:00', close: '24:00' },
            { day: 'tuesday', open: '00:00', close: '24:00' },
            { day: 'wednesday', open: '00:00', close: '24:00' },
            { day: 'thursday', open: '00:00', close: '24:00' },
            { day: 'friday', open: '00:00', close: '24:00' },
            { day: 'saturday', open: '00:00', close: '24:00' },
            { day: 'sunday', open: '00:00', close: '24:00' },
        ],
        phoneNumber: '027-83890123',
    },
    {
        name: '野火咖啡 武汉武昌鱼店',
        description: '以武昌鱼文化为主题的创意咖啡馆，菜单设计融入三国元素。鱼跃龙门拿铁、赤壁战役冷萃等命名极具趣味。店面设计仿古建筑风格，是武汉本土文化自信的体现，深受本地人喜爱。',
        address: '武汉市武昌区武珞路武昌区政府附近武珞路456号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3156, 30.5512] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:30' },
            { day: 'tuesday', open: '09:00', close: '21:30' },
            { day: 'wednesday', open: '09:00', close: '21:30' },
            { day: 'thursday', open: '09:00', close: '21:30' },
            { day: 'friday', open: '09:00', close: '22:00' },
            { day: 'saturday', open: '09:30', close: '22:00' },
            { day: 'sunday', open: '09:30', close: '21:30' },
        ],
        phoneNumber: '027-88234567',
    },
    {
        name: '无名氏书店咖啡馆 武汉武大附近',
        description: '二楼是书店、一楼是咖啡馆的复合空间，藏书以人文社科为主。每月举办读书会和作家见面会，已成为武汉知识分子的精神家园。店内猫咪"卡夫卡"和"萨特"陪伴读者多年，是网红打卡常客。',
        address: '武汉市武昌区珞珈山街道武汉大学旁武汉大学路31号',
        city: '武汉',
        price: 2,
        specialty: 'pour_over',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'pet_friendly'],
        geometry: { type: 'Point', coordinates: [114.3578, 30.5345] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '23:00' },
            { day: 'saturday', open: '10:00', close: '23:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-87234890',
    },
    {
        name: '矿石咖啡 武汉自然博物馆店',
        description: '武汉自然博物馆旁的矿物主题咖啡馆，店内陈列着主理人多年收藏的矿石标本。紫水晶、孔雀石、黄铁矿点缀吧台，营造出独特的地质美学氛围。以矿石命名的系列咖啡颇具创意。',
        address: '武汉市东西湖区金银湖街道武汉自然博物馆附近金银湖路88号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'parking'],
        geometry: { type: 'Point', coordinates: [114.1523, 30.6234] },
        openingHours: [
            { day: 'monday', closed: true },
            { day: 'tuesday', open: '10:00', close: '20:00' },
            { day: 'wednesday', open: '10:00', close: '20:00' },
            { day: 'thursday', open: '10:00', close: '20:00' },
            { day: 'friday', open: '10:00', close: '21:00' },
            { day: 'saturday', open: '09:30', close: '21:00' },
            { day: 'sunday', open: '09:30', close: '20:00' },
        ],
        phoneNumber: '18912345678',
    },
    {
        name: '见字如面咖啡馆 武汉美术学院店',
        description: '湖北美术学院旁的艺术系咖啡馆，主理人是美院插画系毕业生。整面墙的原创手绘壁画每学期更新，展售在校学生的艺术作品。特调饮品名称全部来自艺术史名画，是艺术生们最爱的日常角落。',
        address: '武汉市武昌区昙华林湖北美术学院旁中山路艺术街区8号',
        city: '武汉',
        price: 2,
        specialty: 'latte_art',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3089, 30.5456] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-88567234',
    },
    {
        name: 'Tim Hortons 武汉光谷广场店',
        description: '加拿大国民咖啡品牌，光谷广场店是武汉最繁忙的门店之一。经典双双套餐（双份咖啡+双份甜甜圈）是上班族早餐首选。24小时供应，圆饼/贝果早餐套餐性价比极高，冬季热巧克力不可错过。',
        address: '武汉市洪山区珞瑜路光谷广场地铁站B2口附近',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly', 'wheelchair_accessible'],
        geometry: { type: 'Point', coordinates: [114.3889, 30.5056] },
        openingHours: [
            { day: 'monday', open: '00:00', close: '24:00' },
            { day: 'tuesday', open: '00:00', close: '24:00' },
            { day: 'wednesday', open: '00:00', close: '24:00' },
            { day: 'thursday', open: '00:00', close: '24:00' },
            { day: 'friday', open: '00:00', close: '24:00' },
            { day: 'saturday', open: '00:00', close: '24:00' },
            { day: 'sunday', open: '00:00', close: '24:00' },
        ],
        phoneNumber: '027-87345678',
    },
    {
        name: '椰风咖啡 武汉光谷世界城店',
        description: '以热带海岛风格打造的创意咖啡馆，落叶棕榈和蓝白装饰营造度假感。生椰系列是绝对主角，生椰拿铁、生椰澳白、生椰冷萃全线供应。夏季特调椰奶冻咖啡风靡武汉社交媒体。',
        address: '武汉市洪山区光谷世界城购物中心L1层',
        city: '武汉',
        price: 2,
        specialty: 'cold_brew',
        vibe: 'New Openings',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3956, 30.5012] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '22:00' },
        ],
        phoneNumber: '027-87456789',
    },
    {
        name: '谷雨咖啡 武汉珞珈山文创园店',
        description: '以中国二十四节气为主题的季节性咖啡馆，菜单随节气更换。谷雨季的雨前龙井拿铁、冬至的姜糖美式、春分的樱花冷萃，每款都有诗意叙述。店内陈设融入汉绣和湖北民间艺术元素。',
        address: '武汉市武昌区珞珈山珞珈山文创产业园D栋',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3612, 30.5312] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '09:30', close: '22:00' },
            { day: 'sunday', open: '09:30', close: '21:00' },
        ],
        phoneNumber: '027-87890456',
    },
    {
        name: '一舍咖啡 武汉汉口北店',
        description: '服务汉口北商贸城商圈的实惠咖啡馆，是批发商人和采购员的补给站。超大杯美式15元，小食种类丰富。早餐供应热干面咖啡套餐，是武汉独有的早餐文化体验。',
        address: '武汉市黄陂区汉口北大道武汉国际博览中心附近盘龙城经济开发区88号',
        city: '武汉',
        price: 1,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'air_conditioning', 'no_smoking', 'parking'],
        geometry: { type: 'Point', coordinates: [114.1789, 30.7123] },
        openingHours: [
            { day: 'monday', open: '07:00', close: '21:00' },
            { day: 'tuesday', open: '07:00', close: '21:00' },
            { day: 'wednesday', open: '07:00', close: '21:00' },
            { day: 'thursday', open: '07:00', close: '21:00' },
            { day: 'friday', open: '07:00', close: '21:00' },
            { day: 'saturday', open: '07:30', close: '20:00' },
            { day: 'sunday', open: '07:30', close: '20:00' },
        ],
        phoneNumber: '027-89012345',
    },
    {
        name: '浮生半日咖啡馆 武汉东湖绿道店',
        description: '东湖绿道骑行途中的补给咖啡馆，专为骑行爱好者和跑者设计。提供自行车停放架和运动员专属恢复饮品。椰汁咖啡能量棒和电解质冷萃是招牌，户外大平台可直视东湖水面。',
        address: '武汉市武昌区东湖风景区东湖绿道一期磨山段服务驿站',
        city: '武汉',
        price: 2,
        specialty: 'cold_brew',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'wifi', 'no_smoking', 'parking', 'pet_friendly'],
        geometry: { type: 'Point', coordinates: [114.4012, 30.5189] },
        openingHours: [
            { day: 'monday', open: '07:00', close: '19:00' },
            { day: 'tuesday', open: '07:00', close: '19:00' },
            { day: 'wednesday', open: '07:00', close: '19:00' },
            { day: 'thursday', open: '07:00', close: '19:00' },
            { day: 'friday', open: '07:00', close: '20:00' },
            { day: 'saturday', open: '06:30', close: '20:00' },
            { day: 'sunday', open: '06:30', close: '19:30' },
        ],
        phoneNumber: '18712398765',
    },
    {
        name: '麦隆咖啡 武汉武汉站店',
        description: '武汉高铁站候车区内的精品咖啡馆，为赶车旅客提供快速优质的咖啡服务。训练有素的咖啡师可在3分钟内出品一杯水准以上的拿铁。候车时间不够喝咖啡，带走杯设计保温效果极佳。',
        address: '武汉市洪山区友谊大道武汉站候车室二层',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'wheelchair_accessible'],
        geometry: { type: 'Point', coordinates: [114.4234, 30.5023] },
        openingHours: [
            { day: 'monday', open: '06:00', close: '22:00' },
            { day: 'tuesday', open: '06:00', close: '22:00' },
            { day: 'wednesday', open: '06:00', close: '22:00' },
            { day: 'thursday', open: '06:00', close: '22:00' },
            { day: 'friday', open: '06:00', close: '22:00' },
            { day: 'saturday', open: '06:00', close: '22:00' },
            { day: 'sunday', open: '06:00', close: '22:00' },
        ],
        phoneNumber: '027-87567890',
    },
    {
        name: '桔子咖啡 武汉水果湖店',
        description: '以柑橘元素为主题的阳光系咖啡馆，水果湖行政区旁。橙黄色调的明亮空间让人心情舒畅，橙C美式和橙汁冷萃是全年招牌。店内备有儿童友好角，是亲子下午茶的好去处。',
        address: '武汉市武昌区水果湖街道东湖路水果湖公园旁东湖路145号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'group_friendly', 'outdoor_seating'],
        geometry: { type: 'Point', coordinates: [114.3356, 30.5523] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '21:30' },
            { day: 'saturday', open: '09:00', close: '21:30' },
            { day: 'sunday', open: '09:00', close: '21:00' },
        ],
        phoneNumber: '027-86678901',
    },
    {
        name: '深夜咖啡书店 武汉司门口店',
        description: '武汉第一家以深夜为主题的书店咖啡馆，营业至凌晨3点。夜猫子们的天堂，提供深夜特供的浓度加倍美式和安神玫瑰拿铁。夜间有驻店作家分享创作故事，氛围温暖而神秘。',
        address: '武汉市武昌区司门口解放路司门口商业街附近首义路99号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning', 'laptop_friendly'],
        geometry: { type: 'Point', coordinates: [114.3034, 30.5567] },
        openingHours: [
            { day: 'monday', open: '14:00', close: '03:00' },
            { day: 'tuesday', open: '14:00', close: '03:00' },
            { day: 'wednesday', open: '14:00', close: '03:00' },
            { day: 'thursday', open: '14:00', close: '03:00' },
            { day: 'friday', open: '14:00', close: '04:00' },
            { day: 'saturday', open: '12:00', close: '04:00' },
            { day: 'sunday', open: '12:00', close: '03:00' },
        ],
        phoneNumber: '027-88901234',
    },
    {
        name: '阿拉比卡咖啡 武汉光谷生物城店',
        description: '%Arabica在武汉的旗舰店，坐落于光谷生物城核心地段。极简日式设计风格，以白色和木色为主调。从京都发源的品牌理念"see the world through coffee"在这里得到最好诠释。',
        address: '武汉市洪山区高新大道光谷生物城创新基地附近关东园路99号',
        city: '武汉',
        price: 4,
        specialty: 'specialty_beans',
        vibe: 'Specialty',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.4267, 30.4934] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '21:30' },
            { day: 'saturday', open: '09:00', close: '21:30' },
            { day: 'sunday', open: '09:00', close: '21:00' },
        ],
        phoneNumber: '027-87234567',
    },
    {
        name: '江汉路咖啡角 武汉老租界店',
        description: '位于武汉老租界历史建筑内的欧式咖啡馆，砖墙、壁炉和皮质沙发重现了二十世纪初的生活美学。手冲咖啡和欧式糕点是招牌，提供多国文字菜单。历史与现代在此完美共存。',
        address: '武汉市江岸区江汉路步行街附近兰陵路老租界历史建筑内',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.2978, 30.5934] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:30' },
            { day: 'tuesday', open: '10:00', close: '21:30' },
            { day: 'wednesday', open: '10:00', close: '21:30' },
            { day: 'thursday', open: '10:00', close: '21:30' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:30' },
        ],
        phoneNumber: '027-82890123',
    },
    {
        name: '跑起来咖啡 武汉体育中心店',
        description: '武汉体育中心旁的运动主题咖啡馆，为运动爱好者提供运动前后的能量补给。功能性咖啡饮品（添加MCT油、胶原蛋白、电解质）是特色，提供运动装备展示和售卖区。',
        address: '武汉市洪山区体育馆路武汉体育中心正门对面体育馆路22号',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Outdoor',
        amenities: ['wifi', 'outdoor_seating', 'no_smoking', 'air_conditioning', 'parking'],
        geometry: { type: 'Point', coordinates: [114.3256, 30.5189] },
        openingHours: [
            { day: 'monday', open: '07:00', close: '21:00' },
            { day: 'tuesday', open: '07:00', close: '21:00' },
            { day: 'wednesday', open: '07:00', close: '21:00' },
            { day: 'thursday', open: '07:00', close: '21:00' },
            { day: 'friday', open: '07:00', close: '21:30' },
            { day: 'saturday', open: '06:30', close: '21:30' },
            { day: 'sunday', open: '06:30', close: '21:00' },
        ],
        phoneNumber: '027-86345678',
    },
    {
        name: '第三空间咖啡 武汉天河机场T3店',
        description: '武汉天河机场T3航站楼出发层的候机咖啡馆，是武汉旅客踏上旅途前的最后一杯咖啡。空间开阔明亮，提供高速Wi-Fi和充电设施。招牌武汉热干面拿铁是送别礼物，备受旅客好评。',
        address: '武汉市黄陂区武汉天河国际机场T3航站楼出发层',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'air_conditioning', 'no_smoking', 'wheelchair_accessible'],
        geometry: { type: 'Point', coordinates: [114.2067, 30.7834] },
        openingHours: [
            { day: 'monday', open: '05:30', close: '23:00' },
            { day: 'tuesday', open: '05:30', close: '23:00' },
            { day: 'wednesday', open: '05:30', close: '23:00' },
            { day: 'thursday', open: '05:30', close: '23:00' },
            { day: 'friday', open: '05:30', close: '23:00' },
            { day: 'saturday', open: '05:30', close: '23:00' },
            { day: 'sunday', open: '05:30', close: '23:00' },
        ],
        phoneNumber: '027-96789012',
    },
    {
        name: '禅意咖啡馆 武汉古德寺附近',
        description: '古德寺附近的静心咖啡馆，融合佛教美学与精品咖啡文化。店内供有小佛龛，燃香氛围宁静致远。僧帽拿铁和般若手冲是特色，提供素食轻食。每周日开放免费冥想体验课。',
        address: '武汉市江岸区黄浦大街古德寺附近上海路12号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Hidden Gems',
        amenities: ['quiet', 'no_smoking', 'wifi', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.2956, 30.5878] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '20:00' },
            { day: 'tuesday', open: '09:00', close: '20:00' },
            { day: 'wednesday', open: '09:00', close: '20:00' },
            { day: 'thursday', open: '09:00', close: '20:00' },
            { day: 'friday', open: '09:00', close: '21:00' },
            { day: 'saturday', open: '08:00', close: '21:00' },
            { day: 'sunday', open: '08:00', close: '20:00' },
        ],
        phoneNumber: '027-82345012',
    },
    {
        name: '源野咖啡 武汉后官湖湿地公园店',
        description: '后官湖湿地公园边缘的自然系咖啡馆，四周芦苇荡和候鸟群构成天然背景。全木结构建筑与自然融为一体，提供望远镜供赏鸟使用。鸟鸣声中的一杯手冲，是许多武汉人的周末治愈时光。',
        address: '武汉市蔡甸区后官湖湿地公园东入口旁知音湖大道99号',
        city: '武汉',
        price: 3,
        specialty: 'pour_over',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'parking', 'pet_friendly', 'no_smoking', 'wifi'],
        geometry: { type: 'Point', coordinates: [114.0923, 30.5678] },
        openingHours: [
            { day: 'monday', closed: true },
            { day: 'tuesday', closed: true },
            { day: 'wednesday', open: '09:00', close: '18:00' },
            { day: 'thursday', open: '09:00', close: '18:00' },
            { day: 'friday', open: '09:00', close: '19:00' },
            { day: 'saturday', open: '08:00', close: '19:00' },
            { day: 'sunday', open: '08:00', close: '18:30' },
        ],
        phoneNumber: '18712367890',
    },
    {
        name: '汉阳树咖啡 武汉晴川桥头店',
        description: '以武汉地标"汉阳树"（树龄600年的古银杏）为精神符号的本土品牌，晴川桥头店可见长江与汉江交汇处。江景绝佳，是武汉本地人带外地朋友打卡的首选咖啡地标。',
        address: '武汉市汉阳区晴川街晴川桥汉江入江口旁龟山北路5号',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'wifi', 'no_smoking', 'air_conditioning', 'parking'],
        geometry: { type: 'Point', coordinates: [114.2756, 30.5589] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:30' },
            { day: 'tuesday', open: '09:00', close: '21:30' },
            { day: 'wednesday', open: '09:00', close: '21:30' },
            { day: 'thursday', open: '09:00', close: '21:30' },
            { day: 'friday', open: '09:00', close: '22:30' },
            { day: 'saturday', open: '08:30', close: '22:30' },
            { day: 'sunday', open: '08:30', close: '22:00' },
        ],
        phoneNumber: '027-84123456',
    },
    {
        name: '百草园咖啡 武汉中医药大学店',
        description: '紧邻湖北中医药大学的中医主题咖啡馆，将传统草药与现代咖啡融合。枸杞拿铁、黄芪美式、陈皮冷萃等系列咖啡均经过中医师配伍设计，主打健康功能性咖啡概念。',
        address: '武汉市洪山区黄家湖大道湖北中医药大学旁黄家湖西路88号',
        city: '武汉',
        price: 3,
        specialty: 'espresso',
        vibe: 'Hidden Gems',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.3012, 30.4678] },
        openingHours: [
            { day: 'monday', open: '09:00', close: '21:00' },
            { day: 'tuesday', open: '09:00', close: '21:00' },
            { day: 'wednesday', open: '09:00', close: '21:00' },
            { day: 'thursday', open: '09:00', close: '21:00' },
            { day: 'friday', open: '09:00', close: '21:30' },
            { day: 'saturday', open: '09:30', close: '21:30' },
            { day: 'sunday', open: '09:30', close: '21:00' },
        ],
        phoneNumber: '027-88123456',
    },
    {
        name: '半城烟沙咖啡 武汉沙湖公园店',
        description: '沙湖公园沿岸的诗意咖啡馆，名字取自武汉方言中对江城朦胧晨雾的描述。清晨营业，专为早起人群提供第一杯唤醒咖啡。春天武汉大学樱花季，此处也是赏花骑行后的完美休憩地。',
        address: '武汉市武昌区沙湖公园东门旁团结大道56号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Outdoor',
        amenities: ['outdoor_seating', 'wifi', 'pet_friendly', 'no_smoking', 'parking'],
        geometry: { type: 'Point', coordinates: [114.3267, 30.5678] },
        openingHours: [
            { day: 'monday', open: '07:00', close: '20:00' },
            { day: 'tuesday', open: '07:00', close: '20:00' },
            { day: 'wednesday', open: '07:00', close: '20:00' },
            { day: 'thursday', open: '07:00', close: '20:00' },
            { day: 'friday', open: '07:00', close: '21:00' },
            { day: 'saturday', open: '07:00', close: '21:00' },
            { day: 'sunday', open: '07:00', close: '20:30' },
        ],
        phoneNumber: '027-88789012',
    },
    {
        name: '磁场咖啡 武汉武昌理工学院店',
        description: '武昌理工学院旁的学生向平价精品咖啡馆，主打实惠不妥协品质。学生证享八折优惠，每周二有咖啡盲袋活动。提供打印服务和考研复习专属安静区域，是周边院校学生的第二图书馆。',
        address: '武汉市江夏区藏龙岛武昌理工学院正门旁江夏大道78号',
        city: '武汉',
        price: 1,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'power_outlet', 'laptop_friendly', 'work_friendly', 'quiet', 'no_smoking'],
        geometry: { type: 'Point', coordinates: [114.3389, 30.4512] },
        openingHours: [
            { day: 'monday', open: '08:00', close: '23:00' },
            { day: 'tuesday', open: '08:00', close: '23:00' },
            { day: 'wednesday', open: '08:00', close: '23:00' },
            { day: 'thursday', open: '08:00', close: '23:00' },
            { day: 'friday', open: '08:00', close: '24:00' },
            { day: 'saturday', open: '09:00', close: '24:00' },
            { day: 'sunday', open: '09:00', close: '23:00' },
        ],
        phoneNumber: '18712312345',
    },
    {
        name: '三环路咖啡 武汉汉口火车站店',
        description: '汉口火车站广场对面的便民咖啡馆，面向南来北往的旅客提供快速服务。行李寄存区可免费使用（消费满30元），提供武汉地图和旅游咨询。热干面咖啡礼盒是最受欢迎的武汉伴手礼。',
        address: '武汉市江汉区发展大道汉口火车站站前广场对面解放大道88号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Work-Friendly',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'wheelchair_accessible', 'power_outlet'],
        geometry: { type: 'Point', coordinates: [114.2623, 30.6189] },
        openingHours: [
            { day: 'monday', open: '06:00', close: '22:00' },
            { day: 'tuesday', open: '06:00', close: '22:00' },
            { day: 'wednesday', open: '06:00', close: '22:00' },
            { day: 'thursday', open: '06:00', close: '22:00' },
            { day: 'friday', open: '06:00', close: '22:00' },
            { day: 'saturday', open: '06:00', close: '22:00' },
            { day: 'sunday', open: '06:00', close: '22:00' },
        ],
        phoneNumber: '027-82567012',
    },
    {
        name: '望江咖啡 武汉长江主轴滨江店',
        description: '长江主轴滨江文化区的全景江景咖啡馆，玻璃幕墙正对长江，武汉长江二桥全景入画。落日时分，夕阳将江面染成金色，是武汉最浪漫的咖啡时刻。推荐日落前一小时入座。',
        address: '武汉市武昌区临江大道武汉长江主轴滨江文化区67号',
        city: '武汉',
        price: 4,
        specialty: 'pour_over',
        vibe: 'Specialty',
        amenities: ['wifi', 'air_conditioning', 'no_smoking', 'outdoor_seating', 'group_friendly'],
        geometry: { type: 'Point', coordinates: [114.3089, 30.5612] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '22:00' },
            { day: 'tuesday', open: '10:00', close: '22:00' },
            { day: 'wednesday', open: '10:00', close: '22:00' },
            { day: 'thursday', open: '10:00', close: '22:00' },
            { day: 'friday', open: '10:00', close: '23:00' },
            { day: 'saturday', open: '09:00', close: '23:00' },
            { day: 'sunday', open: '09:00', close: '22:00' },
        ],
        phoneNumber: '027-88012678',
    },
    {
        name: '旧时光咖啡馆 武汉精武路店',
        description: '精武路小巷深处的复古咖啡馆，店主收藏了大量民国时期的武汉老物件。蓄留机器、老式算盘、黑胶唱机构成独特陈设，时光仿佛凝固在此。虹吸壶手工咖啡和自制桂花糕是必点。',
        address: '武汉市硚口区精武路精武肉联厂旧址附近精武路66号',
        city: '武汉',
        price: 2,
        specialty: 'espresso',
        vibe: 'Cozy Vibes',
        amenities: ['wifi', 'quiet', 'no_smoking', 'air_conditioning'],
        geometry: { type: 'Point', coordinates: [114.2545, 30.5756] },
        openingHours: [
            { day: 'monday', open: '10:00', close: '21:00' },
            { day: 'tuesday', open: '10:00', close: '21:00' },
            { day: 'wednesday', open: '10:00', close: '21:00' },
            { day: 'thursday', open: '10:00', close: '21:00' },
            { day: 'friday', open: '10:00', close: '22:00' },
            { day: 'saturday', open: '10:00', close: '22:00' },
            { day: 'sunday', open: '10:00', close: '21:00' },
        ],
        phoneNumber: '027-83456789',
    },
];

// ============================================
// 评论模板库
// ============================================
const reviewTemplates = [
    { content: '环境非常棒，咖啡味道很正，拿铁奶泡细腻，下次还会来。', rating: 5 },
    { content: '手冲咖啡水准很高，能感觉到咖啡师的用心，酸度平衡做得很好。', rating: 5 },
    { content: '第一次来就成为回头客了，氛围安静适合办公，Wi-Fi很稳定。', rating: 5 },
    { content: '豆子新鲜，香气馥郁，美式咖啡喝起来很舒服，不苦不涩。', rating: 4.5 },
    { content: '武汉能有这样水准的精品咖啡馆真的很不容易，支持一下！', rating: 4.5 },
    { content: '冷萃咖啡做得相当出色，口感顺滑层次丰富，夏天的最佳选择。', rating: 4.5 },
    { content: '价格稍贵但品质对得起价格，比某连锁强多了，咖啡师态度也好。', rating: 4 },
    { content: '下午来工作了三个小时，充电方便，咖啡续杯价格优惠，很满意。', rating: 4 },
    { content: '装修风格很有格调，适合拍照，拿铁拉花也漂亮，朋友们都喜欢。', rating: 4 },
    { content: '来武汉出差必打卡，比想象中好很多，难怪本地朋友推荐。', rating: 4 },
    { content: '周末排了半小时队，但喝到之后觉得值了，招牌咖啡确实好喝。', rating: 4 },
    { content: '第一次喝日晒处理的埃塞豆，果香明显，颠覆了我对咖啡的认知。', rating: 5 },
    { content: '咖啡师会介绍豆子产地和处理方式，学到了很多，下次还来。', rating: 4.5 },
    { content: '卡布奇诺比例完美，奶泡绵密，配蛋糕一起吃特别满足。', rating: 4.5 },
    { content: '发现这家店真的赚到了，没什么人却如此安静，是我的秘密基地。', rating: 5 },
    { content: '店猫很可爱，是来这里的额外惊喜，环境温馨让人放松。', rating: 4.5 },
    { content: '冰手冲酸甜平衡做得好，果汁感明显，暑假喝超级爽。', rating: 4 },
    { content: '服务很专业，咖啡师推荐的豆子完全符合我的口味偏好。', rating: 5 },
    { content: '外带杯设计很好看，公司同事都问我在哪买的，下次多打包几杯。', rating: 4 },
    { content: '武汉最好的几家咖啡馆之一，稳定出品，每次来都不失望。', rating: 5 },
    { content: '拿铁味道中规中矩，豆子选用还算不错，但价格略高了一点。', rating: 3.5 },
    { content: '排队等了挺久，但咖啡质量一般，可能是人太多咖啡师手忙脚乱。', rating: 3 },
    { content: '环境不错，咖啡一般，更多是在为氛围付费，不是每次都值。', rating: 3 },
    { content: '第一次来觉得不错，第二次来水准下降明显，出品不稳定。', rating: 3 },
    { content: '位置很好，但生意太好导致咖啡师赶工，质量有所影响。', rating: 3.5 },
    { content: '澳白做得非常好，奶与咖啡比例恰当，浓度适中。', rating: 4.5 },
    { content: '店里有自己的烘焙工坊，能喝到最新鲜的豆子真的很幸福。', rating: 5 },
    { content: '带着笔记本来工作了一整天，没被催走，太nice了。', rating: 4.5 },
    { content: '景观绝佳，咖啡也配得上，是武汉少有的景色与品质双赢的店。', rating: 5 },
    { content: '菜单太短了，希望多一些选择，但现有的每款都有用心做。', rating: 3.5 },
    { content: '武汉本土品牌要多多支持，出品和北上广的精品咖啡馆完全不相上下。', rating: 4.5 },
    { content: '隐藏在小巷里找了好久，但这种藏着掖着的感觉反而让咖啡更香。', rating: 4.5 },
    { content: '燕麦拿铁做得比牛奶版本还好喝，奶泡质地完全不同档次。', rating: 4 },
    { content: '朋友从北京来玩，带他来喝了这家，他说比北京某些精品咖啡馆还好。', rating: 5 },
    { content: '停车不方便是唯一的缺点，咖啡本身无可挑剔。', rating: 4 },
    { content: '可以看到咖啡师冲泡全过程，透明厨房让人放心。', rating: 4.5 },
    { content: '夏天的特调冰饮做得很创意，没有喝到过类似的口感。', rating: 4 },
    { content: '三种不同产区的单品手冲对比喝了一遍，体验很值得。', rating: 5 },
    { content: '服务员对咖啡知识掌握扎实，回答问题很专业，好感倍增。', rating: 4.5 },
    { content: '包装很好看，作为礼物送给朋友超合适，下次继续来。', rating: 4 },
    { content: '附近上班已经来了20多次，每次都是固定几款，从未失望过。', rating: 5 },
    { content: '洗手间干净整洁，细节处见用心，是对待顾客认真的体现。', rating: 4 },
    { content: '比较吵闹不适合工作，但作为约会聊天场所体验很好。', rating: 3.5 },
    { content: '武汉三伏天能有这么舒服的空调和咖啡，简直是天堂。', rating: 4.5 },
    { content: '独家口味的武汉特调必须点，把城市文化融入咖啡的理念很棒。', rating: 4.5 },
    { content: '门口没有明显招牌，第一次差点路过，发现之后每周必来。', rating: 4.5 },
    { content: '价格亲民品质不低，是武汉咖啡性价比之王，学生党首选。', rating: 4.5 },
    { content: '店内绿植很多，坐在里面非常有生命力，咖啡也充满活力。', rating: 4 },
    { content: '周末来得早才有好位置，建议提前来，不然只能站着等。', rating: 3.5 },
    { content: '蜂蜜燕麦拿铁是隐藏菜单，需要直接问咖啡师，比正式菜单好喝。', rating: 5 },
];

// ============================================
// 虚拟用户数据（用于关联评论）
// ============================================
const reviewAuthors = [
    { username: 'wuhan_coffee_fan', email: 'coffee_fan@test.com' },
    { username: 'donghu_walker', email: 'donghu@test.com' },
    { username: 'guanggu_coder', email: 'coder@test.com' },
    { username: 'wuda_student', email: 'wuda@test.com' },
    { username: 'hankou_foodie', email: 'foodie@test.com' },
    { username: 'wuhan_barista', email: 'barista@test.com' },
    { username: 'changjiang_drifter', email: 'river@test.com' },
    { username: 'luojiashan_hiker', email: 'hiker@test.com' },
    { username: 'tianhe_traveler', email: 'traveler@test.com' },
    { username: 'shuiguohu_local', email: 'local@test.com' },
    { username: 'hanyang_designer', email: 'designer@test.com' },
    { username: 'wuchang_writer', email: 'writer@test.com' },
    { username: 'jiangan_photographer', email: 'photo@test.com' },
    { username: 'qingchuan_runner', email: 'runner@test.com' },
    { username: 'dongfeng_engineer', email: 'engineer@test.com' },
];

// ============================================
// Seed 主函数
// ============================================
const seedWuhanCafes = async () => {
    const User = mongoose.model('User', require('../models/user').default?.schema || new mongoose.Schema({
        username: String, email: String, password: String, role: String,
        favorites: [mongoose.Schema.Types.ObjectId],
        visited: [{ cafe: mongoose.Schema.Types.ObjectId, visitedAt: Date }],
        preferences: mongoose.Schema.Types.Mixed,
        isActive: { type: Boolean, default: true },
        isEmailVerified: { type: Boolean, default: true },
    }));

    // 动态 require 模型
    let Cafe, Review, UserModel;
    try {
        Cafe = mongoose.models.Cafe || (await import('../models/cafe.js')).default;
        Review = mongoose.models.Review || (await import('../models/review.js')).default;
        UserModel = mongoose.models.User;
    } catch {
        console.log('使用 require 加载模型...');
    }

    // 创建或获取虚拟用户
    console.log('👤 创建虚拟用户...');
    const userIds = [];
    for (const author of reviewAuthors) {
        let user = await UserModel.findOne({ email: author.email });
        if (!user) {
            user = await UserModel.create({
                username: author.username,
                email: author.email,
                password: '$2a$10$XfE4L8gRFn3V7iMdKq1R5.placeholder.hash.for.seed',
                role: 'user',
                isActive: true,
                isEmailVerified: true,
                favorites: [],
                visited: [],
                preferences: {
                    learned: { favoriteAmenities: [], favoriteSpecialties: [], priceRange: { min: 1, max: 4 }, atmospherePreferences: [] },
                    manual: { dietaryRestrictions: [], mustHaveAmenities: [], avoidAmenities: [], preferredCities: [] },
                    lastUpdated: new Date(),
                    confidence: 0,
                }
            });
        }
        userIds.push(user._id);
    }
    console.log(`✅ 已准备 ${userIds.length} 个虚拟用户`);

    // 找一个 admin 用户作为咖啡馆 owner，没有就用第一个虚拟用户
    let ownerUser = await UserModel.findOne({ role: 'admin' });
    if (!ownerUser) ownerUser = await UserModel.findOne({ email: reviewAuthors[0].email });
    const ownerId = ownerUser._id;

    console.log('\n☕ 开始插入武汉咖啡馆数据...\n');
    let cafeCount = 0;
    let reviewCount = 0;

    for (const cafeData of wuhanCafes) {
        // 创建咖啡馆
        const cafe = await Cafe.create({
            ...cafeData,
            author: ownerId,
            images: [
                {
                    url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
                    filename: `wuhan_cafe_${cafeCount + 1}_1`,
                    publicId: `sipspot/wuhan/${cafeCount + 1}_1`
                },
                {
                    url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
                    filename: `wuhan_cafe_${cafeCount + 1}_2`,
                    publicId: `sipspot/wuhan/${cafeCount + 1}_2`
                }
            ],
            rating: 0,
            reviewCount: 0,
            reviews: [],
        });

        // 为每家咖啡馆生成 10-14 条评论
        const numReviews = 10 + Math.floor(Math.random() * 5);
        const shuffled = [...reviewTemplates].sort(() => Math.random() - 0.5);
        const selectedReviews = shuffled.slice(0, numReviews);

        const reviewIds = [];
        let totalRating = 0;

        for (let i = 0; i < selectedReviews.length; i++) {
            const template = selectedReviews[i];
            const authorId = userIds[i % userIds.length];

            // 评分在模板基础上加一点随机波动
            const ratingVariation = (Math.random() - 0.5) * 0.5;
            const rawRating = template.rating + ratingVariation;
            const rating = Math.round(Math.min(5, Math.max(1, rawRating)) * 2) / 2;

            const review = await Review.create({
                content: template.content,
                rating,
                cafe: cafe._id,
                author: authorId,
                detailedRatings: {
                    coffee: Math.min(5, Math.max(1, Math.round((rating + (Math.random() - 0.5) * 1) * 2) / 2)) || 3,
                    ambience: Math.min(5, Math.max(1, Math.round((rating + (Math.random() - 0.5) * 1) * 2) / 2)) || 3,
                    service: Math.min(5, Math.max(1, Math.round((rating + (Math.random() - 0.5) * 1) * 2) / 2)) || 3,
                    value: Math.min(5, Math.max(1, Math.round((rating + (Math.random() - 0.5) * 1) * 2) / 2)) || 3,
                },
                aiAnalysis: {
                    sentiment: rating >= 4 ? 'positive' : rating >= 3 ? 'neutral' : 'negative',
                    keywords: rating >= 4
                        ? ['好喝', '推荐', '环境好']
                        : rating >= 3
                        ? ['一般', '可以', '还行']
                        : ['失望', '不推荐'],
                    summary: template.content.slice(0, 50) + '...',
                    confidence: 0.85,
                },
                createdAt: new Date(Date.now() - Math.random() * 180 * 24 * 60 * 60 * 1000),
            });

            reviewIds.push(review._id);
            totalRating += rating;
            reviewCount++;
        }

        // 更新咖啡馆评分
        const avgRating = Math.round((totalRating / reviewIds.length) * 10) / 10;
        await Cafe.findByIdAndUpdate(cafe._id, {
            reviews: reviewIds,
            reviewCount: reviewIds.length,
            rating: avgRating,
        });

        cafeCount++;
        console.log(`✅ [${cafeCount}/50] ${cafe.name} — ${reviewIds.length}条评论 — 评分${avgRating}`);
    }

    console.log(`\n🎉 武汉咖啡馆数据插入完成！`);
    console.log(`   咖啡馆: ${cafeCount} 家`);
    console.log(`   评论:   ${reviewCount} 条`);
    console.log(`   平均每家: ${(reviewCount / cafeCount).toFixed(1)} 条评论\n`);
};

// ============================================
// 执行
// ============================================
mongoose.connect(MONGODB_URI)
    .then(async () => {
        console.log('✅ MongoDB 连接成功\n');

        // 动态 import ESM 模型
        const { default: Cafe } = await import('../models/cafe.js');
        const { default: Review } = await import('../models/review.js');
        const { default: UserModel } = await import('../models/user.js');

        // 挂载到 mongoose.models 供 seedWuhanCafes 使用
        if (!mongoose.models.Cafe) mongoose.model('Cafe', Cafe.schema);
        if (!mongoose.models.Review) mongoose.model('Review', Review.schema);
        if (!mongoose.models.User) mongoose.model('User', UserModel.schema);

        await seedWuhanCafes();
    })
    .catch(err => {
        console.error('❌ 连接失败:', err.message);
        process.exit(1);
    })
    .finally(() => mongoose.connection.close());
